### ISSUE TITLE
Publish a chapter on extending Zowe using the Cupids lifecycle

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#1099] opened 2020-04-02 12:26 UTC
## Is your request for enhancement related to a problem? Please describe.
Cupids introduced a new lifecy

## Describe the solution you'd like
New doc chapter to describe this, and also update the API ML static definition extension docs

**Comment by nannanli** [comment] 2020-04-21 09:25
Duplicate of #998

**Closed** 2020-05-15 14:46 UTC
