### ISSUE TITLE
Update architecture section to help troubleshooting and explain subsystems more

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#454] opened 2019-04-02 21:34 UTC
## Is your request for enhancement related to a problem? Please describe.
When doing troubleshooting with users the architecture and ports and network flow and where logs are written is useful to share with them to help diagnose

## Describe the solution you'd like
Create a new section in the docs to explain the architecture in more detail with the network traffic and logs to help diagnosis of problems

## Additional context

**Comment by nannanli** [comment] 2020-02-18 06:53
Duplicate of #737 . Closing this one.

**Closed by nannanli** 2020-02-18 06:53 UTC
Labels: docs
