### ISSUE TITLE
tssFacilityOwner is not documented

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#772] opened 2019-10-17 16:05 UTC
## Description

The description for the parameter `TSS Facility Owner` in file `zowe-install-apf-server.yaml` is not documented.  
## Pages to Update

```
# APF server users
users:
  # User to run Zowe server (required, no default values)
  zoweUser=IZUSVR
  # TSS Facility Owner (Required for TSS. 'auto' supplies the running user)
  tssFacilityOwner=auto
```

## Expected behavior

Documentation for this field should be added.  
## Additional context

This is a new field.

**Comment by John-A-Davies** [comment] 2019-10-18 10:13
Duplicate of #727?

**Comment by nannanli** [comment] 2019-10-22 06:07
Hey @John-A-Davies, yes, this is a duplicate of #727 . Working on 727 now.

**Closed by nannanli** 2019-10-22 06:07 UTC
