### ISSUE TITLE
Unable to see previous docs from zowe.org for releases 1.6 onwards.  

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#1069] opened 2020-03-03 12:43 UTC
## Description
https://www.zowe.org/#documentation
twistie expand Past Release 
navigate to documentation hyperlink for releases 1.6, 1.7, 1.7.1 and 1.8.
unable to open docs correctly.  It works for 1.5 and earlier releases.

## Pages to Update
https://www.zowe.org/#documentation

## Screenshots
![image](https://user-images.githubuserc

select 1.6 that opens the URL https://docs.zowe.org/stable/v-1-6-x
The page tries to redirect to https://docs.zowe.org/stable/v-1-6-x (i.e. itself).

![image](https://user-images.githubusercontent.com/28100302/75776529-15088900-5d4c-11ea-932f-a015ec4dd7df.png)
ontent.com/28100302/75776480-04f0a980-5d4c-11ea-8e00-c6f87b16cd20.png)

**Comment by nannanli** [comment] 2020-03-19 10:18
Thanks you for catching this! It is caused by an extra `-` before the version number. A PR has been created to fix this issue. https://github.com/zowe/zowe.github.io/pull/83

**Comment by nannanli** [comment] 2020-03-20 14:37
Verified that this issue has been resolved on zowe.org. Closing.

**Closed by nannanli** 2020-03-20 14:37 UTC
