### ISSUE TITLE
Zowe job names formats are documented inconsistently 

### ISSUE THREAD

**Issue by hockeyrob** [zowe/docs-site#2279] opened 2022-07-18 19:19 UTC
## Description
This page references zowe.jobname from the YAML file. There is no such parameter. There is a zowe.job.name. Looks like this was missed in the migration to Zowe 2.0.0

## Pages to Update
https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe-stop

## Expected behavior
Please update this page so it matches the current zowe.yaml file configuration

**Comment by nannanli** [comment] 2022-07-28 06:33
Thank you for raising this issue! 
@jackjia-ibm Should the reference to `zowe.jobname` be changed to `zowe.job.name` on page https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe-stop. Just checked the YAML configuration file reference, it uses `zowe.job.name` there so these two do not match at the moment.

**Comment by jackjia-ibm** [comment] 2022-07-28 13:25
Duplicate of #2280.

Should be fixed with https://github.com/zowe/zowe-install-packaging/pull/2973.

**Closed** 2023-02-09 09:58 UTC
Labels: type: bug, area: zos-install-upgrade
