### ISSUE TITLE
Improve the Using Zowe Explorer doc

### ISSUE THREAD

**Issue by IgorCATech** [zowe/docs-site#1474] opened 2020-11-05 16:10 UTC
## Is your request for enhancement related to a problem? Please describe.

Some of the Zowe Explorer functionalities are not covered and supported by Gifs in the doc. Also, it would be great to add hyperlinks to the list of functionalities for better navigation and user experience. 

## Describe the solution you'd like

Add missing descriptions/procedures. For example, the "Submit a JCL" feature is not covered in the doc. Add links to the lists of functionalities in the DS, USS, and JOB sections.

## Related doc pages
https://docs.zowe.org/stable/user-guide/ze-usage.html#sample-use-cases

**Comment by anaxceron** [comment] 2023-04-10 18:39
@IgorCATech -- the use case content has been reorganized into its own page: [Sample use cases](https://docs.zowe.org/stable/user-guide/ze-use-cases)

I think more gifs have been added since your issue was filed, and links you suggested have also been added. Can you please review to confirm whether your issue has already been addressed?

**Comment by anaxceron** [comment] 2023-04-11 17:52
Closing issue as items have already been addressed, which has been confirmed by @IgorCATech.

**Closed by anaxceron** 2023-04-11 17:52 UTC
Labels: area: zowe-explorer
